import React, { useState } from 'react';
import { TextField, Button, Dialog, DialogActions, DialogContent, DialogTitle } from '@mui/material';
import { ILeaseDetail } from '../interface/ILeaseDetail'; // Ensure this interface is defined

interface AddLeaseProps {
  open: boolean;
  onClose: () => void;
  onSave: (lease: ILeaseDetail) => void;
}

const AddLease: React.FC<AddLeaseProps> = ({ open, onClose, onSave }) => {
  const [newLease, setNewLease] = useState<ILeaseDetail>({
    id: '', // Assuming ID might be generated by the backend or not needed for a new entry
    device_id: '',
    lessor: '',
    contract_id: '',
    start_date: '',
    comment: '',
    lease_start: '',
    lease_end: '',
  });

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target;
    setNewLease({ ...newLease, [name]: value });
  };

  const handleSave = () => {
    onSave(newLease);
    onClose(); // Close the dialog after saving
    // Optionally reset the form to initial state
    setNewLease({
      id: '',
      device_id: '',
      lessor: '',
      contract_id: '',
      start_date: '',
      comment: '',
      lease_start: '',
      lease_end: '',
    });
  };

  return (
    <Dialog open={open} onClose={onClose}>
      <DialogTitle>Add New Lease</DialogTitle>
      <DialogContent>
        <TextField label="Device ID" name="device_id" value={newLease.device_id} onChange={handleChange} fullWidth margin="dense" />
        <TextField label="Lessor" name="lessor" value={newLease.lessor} onChange={handleChange} fullWidth margin="dense" />
        <TextField label="Contract ID" name="contract_id" value={newLease.contract_id} onChange={handleChange} fullWidth margin="dense" />
        <TextField label="Start Date" name="start_date" type="date" InputLabelProps={{ shrink: true }} value={newLease.start_date} onChange={handleChange} fullWidth margin="dense" />
        <TextField label="Comment" name="comment" value={newLease.comment} onChange={handleChange} fullWidth margin="dense" />
        <TextField label="Lease Start" name="lease_start" type="date" InputLabelProps={{ shrink: true }} value={newLease.lease_start} onChange={handleChange} fullWidth margin="dense" />
        <TextField label="Lease End" name="lease_end" type="date" InputLabelProps={{ shrink: true }} value={newLease.lease_end} onChange={handleChange} fullWidth margin="dense" />
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose}>Cancel</Button>
        <Button onClick={handleSave}>Save</Button>
      </DialogActions>
    </Dialog>
  );
};

export default AddLease;
